cargo-features = ["strip"]

[package]
name = "isar-core-dart-ffi"
version = "0.0.0"
authors = ["Simon Leier <simonleier@gmail.com>"]
edition = "2018"

[dependencies]
isar-core = { path = "../" }
float_next_after = "0.1.5"
threadpool = "1.8.1"
once_cell = "1.7.1"
serde_json = "1.0.64"
byteorder = "1"

[lib]
crate-type=["staticlib", "cdylib"]

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"