name: Build release binaries

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload:
    name: Build and upload
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            artifact_name: libisar_android_arm64.so
            script: build_android.sh
          - os: macos-latest
            artifact_name: libisar_android_x64.so
            script: build_android.sh x64
          - os: macos-latest
            artifact_name: libisar_ios.a
            script: build_ios.sh
          - os: ubuntu-latest
            artifact_name: libisar_linux_x64.so
            script: build_desktop.sh
         #- os: macos-latest
         #  artifact_name: libisar_macos_arm64.dylib
         #  script: build_desktop.sh
          - os: macos-latest
            artifact_name: libisar_macos_x64.dylib
            script: build_desktop.sh x64
         #- os: windows-latest
          # artifact_name: isar_windows_x64.dll
          # script: build_desktop.sh
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Build
      working-directory: dart-ffi
      run: bash tools/${{ matrix.script }}
    - name: Upload binary
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dart-ffi/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.artifact_name }}
        tag: ${{ github.ref }}
