name: Rust CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: install nasm
      if: matrix.os == 'windows-latest'
      run: choco install nasm
    - uses: actions-rs/cargo@v1
      name: test
      with:
        command: test
        args: --verbose
    - uses: actions-rs/cargo@v1
      name: test encryption
      with:
        command: test
        args: --verbose --features test-encryption
